spring.application.name=payment-service
server.port=8087

# Resilience4j Properties for paymentService instance
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=5s
