server.port=9090
spring.application.name=api-gateway

# Enable discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
