spring.application.name=api-gateway
server.port=8080

# Customer Service Route
spring.cloud.gateway.routes[0].id=customer_route
spring.cloud.gateway.routes[0].uri=http://localhost:8085
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/customers/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/(?<segment>.*), /$\\{segment}
spring.cloud.gateway.routes[0].filters[1]=RateLimit=5
spring.cloud.gateway.routes[0].filters[2]=Cache=120

# Billing Service Route
spring.cloud.gateway.routes[1].id=billing_route
spring.cloud.gateway.routes[1].uri=http://localhost:8086
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/billing/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/(?<segment>.*), /$\\{segment}
spring.cloud.gateway.routes[1].filters[1]=RateLimit=5
spring.cloud.gateway.routes[1].filters[2]=Cache=60
